name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build-and-test:
    runs-on: self-hosted

    container:
      image: rust:latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Install Python
        run: |
          apt-get update
          apt-get install -y python3 python3-pip
    
      - name: Run Python script
        run: python3 main.py
    
      - name: Run tests
        run: cargo test --verbose
