name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build-and-test:
    runs-on: self-hosted
    container:
      image: rust:latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Python environment
        run: |
          apt-get update
          apt-get install -y python3-venv python3-dev
        shell: bash
    
      - name: Install Python dependencies
        run: pip3 install termcolor
        shell: bash

      - name: Process example schemas
        run: |
          for schema in example_schemas/*.xml; do
            echo "Processing $schema"
            python3 main.py "$schema"
          done
        shell: bash
