name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build-and-test:
    runs-on: self-hosted
    container:
      image: rust:latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Python environment
        run: |
          apt-get update
          apt-get install -y python3-venv
          python3 -m venv venv
        shell: bash
    
      - name: Install Python dependencies
        run: |
          . venv/bin/activate
          pip install maturin pytest
        shell: bash

      - name: Generate Rust code 1
        run: |
          . venv/bin/activate
          python3 main.py example_schemas/school.xml
        shell: bash
      
      - name: Run Rust tests 1
        run: cargo test --verbose

      - name: Generate example output 1
        run: cargo run --verbose
      
      - name: Generate Python bindings 1
        run: |
          . venv/bin/activate
          maturin develop
        shell: bash

      - name: Run Python tests 1
        run: |
          . venv/bin/activate
          pytest
        shell: bash

      - name: Generate Rust code 2
        run: |
          . venv/bin/activate
          python3 main.py example_schemas/trading.xml
        shell: bash
      
      - name: Run Rust tests 2
        run: cargo test --verbose

      - name: Generate example output 2
        run: cargo run --verbose
      
      - name: Generate Python bindings 2
        run: |
          . venv/bin/activate
          maturin develop
        shell: bash

      - name: Run Python tests 2
        run: |
          . venv/bin/activate
          pytest
        shell: bash
