name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build-and-test:
    runs-on: self-hosted

    container:
      image: rust:latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Install Python
        run: |
          apt-get update
          apt-get install -y python3 python3-pip python3-venv
          python3 -m venv venv
          source venv/bin/activate
          pip install maturin pytest

      - name: Generate Rust code 1
        run: python3 main.py example_schemas/school.xml
      
      - name: Run Rust tests 1
        run: cargo test --verbose

      - name: Generate example output 1
        run: cargo run --verbose
      
      - name: Generate Python bindings 1
        run: maturin develop

      - name: Run Python tests 1
        run: pytest

      - name: Generate Rust code 2
        run: python3 main.py example_schemas/trading.xml
      
      - name: Run Rust tests 2
        run: cargo test --verbose

      - name: Generate example output 2
        run: cargo run --verbose
      
      - name: Generate Python bindings 2
        run: maturin develop

      - name: Run Python tests 2
        run: pytest
