name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build-and-test:
    runs-on: self-hosted
    # container:
      # image: rust:latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Build and Run with Docker
        run: |
          docker build -t xparse-image .
          for schema in example_schemas/*.xml; do
            echo "Processing $schema"
            docker run --rm xparse-image python3 main.py "$schema"
          done
